export {default as Home}  from './Home';
export {default as HistoryPage} from './HistoryPage';
export {default as UploadVideo} from './UploadVideo';
export {default as SingleChannelAbout} from './SingleChannelAbout';
export {default as UserAccountPage} from './UserAccountPage';
export {default as SingleVideoPage} from './SingleVideoPage';
export {default as UploadEdit} from './UploadEdit';
export {default as SearchedVideoPage} from './SearchedVideoPage';
export {default as BrowserChannels} from './BrowseChannels';